### ISSUE TITLE
Big padding when 5000 characters or more

### ISSUE THREAD

**Issue by melvinvandenbout** [myang-git/QR-Code-Encoder-for-Objective-C#6]
When I encode something between 6000 and 7,089 numeric characters the padding on the UIImage is like 2/3 of the image. Are you aware of this problem and is there a fix?

**Comment by myang-git** [comment]
Yes this is expected but also depends on the size of the image. Encoding 6000+ characters requires a lot of dots. The QR code renderer has to evenly distribute the width and height to each dot, and since the pixel-size of the dot is integer, there will be some error in this distribution. The more dots you have the higher error it will add up. This is why you see big padding in the image. Making the image size larger may help.
